### ISSUE TITLE
having a problem running the sample code

### ISSUE THREAD

**Issue by dicook** [huizezhang-sherry/quickdraw#1]
> qd_sample(c("octopus", "star"), 5)
Downloading octopus.ndjson with cloudml
Error in gsutil_binary() : failed to find 'gsutil' binary

looks like i need to install something else

**Comment by huizezhang-sherry** [comment]
Yes, Google Cloud SDK is needed.  Try `cloudml::gcloud_install()` before sampling.

**Comment by dicook** [comment]
Awesome,  this really works!

(Get ready for the next issue, coming.)

**Comment by abalamur** [comment]
`library(quickdraw)
library(cloudml)

bread <- qd_read("bread")


Downloading bread.ndjson with cloudml
Error in gsutil_binary() : failed to find 'gsutil' binary`

I am trying to use the qd_read() function but it keeps throwing the same error. Is there something else I need to download?

I also tried using `cloudml::gcloud_install()` but that did not fix the issue.
