### ISSUE TITLE
Issue using qd_read function

### ISSUE THREAD

**Issue by abalamur** [huizezhang-sherry/quickdraw#4]
`library(quickdraw)`
`library(cloudml)`
`bread <- qd_read("bread")`

`Downloading bread.ndjson with cloudml`
`Error in gsutil_binary() : failed to find 'gsutil' binary`

I am trying to use the qd_read() function but it keeps throwing the same error. Is there something else I need to download?

I also tried using cloudml::gcloud_install() but that did not fix the issue.

**Comment by huizezhang-sherry** [comment]
I think it's a problem with gcloud installation. Have you been successfully completed the `cloudml::gcloud_install()`?

Your commands work from my side and produce a `bread`tibble with 120,570 rows and 6 variables


<img width="748" alt="Screen Shot 2020-07-15 at 13 10 51" src="https://user-images.githubusercontent.com/36781502/87499071-af82bc80-c69c-11ea-8726-f250d2fa703f.png">

**Comment by sa-lee** [comment]
@huizezhang-sherry maybe you should document in the readme, the need to have the gsutil binary installed and how to do it

**Comment by huizezhang-sherry** [comment]
good idea, it's now on
